// <auto-generated />
namespace ITIProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatelession3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatelession3));
        
        string IMigrationMetadata.Id
        {
            get { return "202010112339569_update-lession3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
