// <auto-generated />
namespace ITIProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateSetup4_addStudent4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateSetup4_addStudent4));
        
        string IMigrationMetadata.Id
        {
            get { return "202009301639007_update-Setup4_addStudent4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
